### ISSUE TITLE
Database Exception – yii\db\Exception

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub-modules-reportcontent#14]
Humhub: 1.1.0-dev
![screenshot_20160517-202536](https://cloud.githubusercontent.com/assets/7725575/15332266/94f5fa9a-1c6d-11e6-83a5-35d34085c8c6.png)

**Comment by cagatayldzz** [comment]
@luke- 
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'super_admin' in 'where clause'' in /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/db/Command.php:900 Stack trace: #0 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/db/Command.php(900): PDOStatement->execute() #1 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/db/Command.php(376): yii\db\Command->queryInternal('fetch', NULL) #2 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/db/Query.php(247): yii\db\Command->queryOne() #3 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(290): yii\db\Query->one(NULL) #4 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(107): yii\db\ActiveQuery->one() #5 /home/ubuntu/workspace/protected/modules/reportcontent/models/ReportContent.php(140): yii\db\BaseActiveRecord::findOne(Array) #6 /home/ubuntu/workspace/protected/modules/reportcontent/widgets/ReportContentWidget.php(31): humhub\modules\reportcontent\models\ReportContent::canReportPost(8) #7 /home/ubuntu/workspace/protected/humhub/components/Widget.php(52): humhub\modules\reportcontent\widgets\ReportContentWidget->run() #8 /home/ubuntu/workspace/protected/humhub/widgets/BaseStack.php(92): humhub\components\Widget::widget(Array) #9 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/Widget.php(98): humhub\widgets\BaseStack->run() #10 /home/ubuntu/workspace/protected/humhub/modules/content/widgets/views/wallEntry.php(21): yii\base\Widget::widget(Array) #11 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/View.php(325): require('/home/ubuntu/wo...') #12 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/ubuntu/wo...', Array) #13 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/ubuntu/wo...', Array, Object(humhub\modules\post\widgets\WallEntry)) #14 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/Widget.php(191): yii\base\View->render('@humhub/modules...', Array, Object(humhub\modules\post\widgets\WallEntry)) #15 /home/ubuntu/workspace/protected/humhub/modules/content/widgets/WallEntry.php(112): yii\base\Widget->render('@humhub/modules...', Array) #16 /home/ubuntu/workspace/protected/humhub/modules/content/components/ContentActiveRecord.php(124): humhub\modules\content\widgets\WallEntry->renderWallEntry() #17 /home/ubuntu/workspace/protected/humhub/modules/content/components/actions/Stream.php(253): humhub\modules\content\components\ContentActiveRecord->getWallOut() #18 [internal function]: humhub\modules\content\components\actions\Stream->run() #19 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array) #20 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array) #21 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('stream', Array) #22 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('dashboard/dashb...', Array) #23 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #24 /home/ubuntu/workspace/index.php(25): yii\base\Application->run() #25 {main} Next exception 'yii\db\Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'super_admin' in 'where clause' The SQL being executed was: SELECT * FROM `user` WHERE (`id`=1) AND (`super_admin`=1)' in /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/db/Schema.php:633 Stack trace: #0 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/db/Command.php(915): yii\db\Schema->convertException(Object(PDOException), 'SELECT * FROM `...') #1 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/db/Command.php(376): yii\db\Command->queryInternal('fetch', NULL) #2 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/db/Query.php(247): yii\db\Command->queryOne() #3 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(290): yii\db\Query->one(NULL) #4 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(107): yii\db\ActiveQuery->one() #5 /home/ubuntu/workspace/protected/modules/reportcontent/models/ReportContent.php(140): yii\db\BaseActiveRecord::findOne(Array) #6 /home/ubuntu/workspace/protected/modules/reportcontent/widgets/ReportContentWidget.php(31): humhub\modules\reportcontent\models\ReportContent::canReportPost(8) #7 /home/ubuntu/workspace/protected/humhub/components/Widget.php(52): humhub\modules\reportcontent\widgets\ReportContentWidget->run() #8 /home/ubuntu/workspace/protected/humhub/widgets/BaseStack.php(92): humhub\components\Widget::widget(Array) #9 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/Widget.php(98): humhub\widgets\BaseStack->run() #10 /home/ubuntu/workspace/protected/humhub/modules/content/widgets/views/wallEntry.php(21): yii\base\Widget::widget(Array) #11 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/View.php(325): require('/home/ubuntu/wo...') #12 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/ubuntu/wo...', Array) #13 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/ubuntu/wo...', Array, Object(humhub\modules\post\widgets\WallEntry)) #14 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/Widget.php(191): yii\base\View->render('@humhub/modules...', Array, Object(humhub\modules\post\widgets\WallEntry)) #15 /home/ubuntu/workspace/protected/humhub/modules/content/widgets/WallEntry.php(112): yii\base\Widget->render('@humhub/modules...', Array) #16 /home/ubuntu/workspace/protected/humhub/modules/content/components/ContentActiveRecord.php(124): humhub\modules\content\widgets\WallEntry->renderWallEntry() #17 /home/ubuntu/workspace/protected/humhub/modules/content/components/actions/Stream.php(253): humhub\modules\content\components\ContentActiveRecord->getWallOut() #18 [internal function]: humhub\modules\content\components\actions\Stream->run() #19 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array) #20 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array) #21 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('stream', Array) #22 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('dashboard/dashb...', Array) #23 /home/ubuntu/workspace/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #24 /home/ubuntu/workspace/index.php(25): yii\base\Application->run() #25 {main} Additional Information: Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column 'super_admin' in 'where clause' )
